#!/usr/bin/env python3
# encoding: utf-8

# (c) Wiltrud Kessler, 5.11.13
# Do with this code whatever you want :)

"""
Create an ILIAS question pool from a text file
(because doing this in ILIAS is annoying).

You will get an XML file that you can import into ILIAS.
"""

import os
import re
import sys
import argparse
import zipfile
import shutil
import io
import csv
import hashlib
from fractions import Fraction


header = '<?xml version="1.0" encoding="utf-8"?>\n<!DOCTYPE questestinterop SYSTEM "ims_qtiasiv1p2p1.dtd">\n<!--Generated by ILIAS XmlWriter-->\n<questestinterop>\n'

footer = "</questestinterop>\n"

# For the whole question (open/close)
itemopen = (
    '  <item ident="%s" title="%s" maxattempts="1">\n'  # depending on title and id
)
itemclose = "  </item>\n"

# textgaprating = ci -> case insensitive
# textgaprating = cs -> case sensitive

# Metadata (whole question, tpye, other info)
questionTypeGap = "CLOZE QUESTION"
questionTypeMCSingle = "SINGLE CHOICE QUESTION"
questionTypeMCMulti = "MULTIPLE CHOICE QUESTION"
itemmetadata = "    <qticomment/>\n    <duration>P0Y0M0DT0H1M0S</duration>\n    <itemmetadata>\n      <qtimetadata>\n        <qtimetadatafield>\n          <fieldlabel>ILIAS_VERSION</fieldlabel>\n          <fieldentry>9.18.0</fieldentry>\n        </qtimetadatafield>\n        <qtimetadatafield>\n          <fieldlabel>QUESTIONTYPE</fieldlabel>\n          <fieldentry>%s</fieldentry>\n        </qtimetadatafield>\n        <qtimetadatafield>\n          <fieldlabel>AUTHOR</fieldlabel>\n          <fieldentry>TIQI - The ILIAS Question Importer</fieldentry>\n        </qtimetadatafield>\n        <qtimetadatafield>\n          <fieldlabel>textgaprating</fieldlabel>\n          <fieldentry>cs</fieldentry>\n        </qtimetadatafield>\n        <qtimetadatafield>\n          <fieldlabel>fixedTextLength</fieldlabel>\n          <fieldentry/>\n        </qtimetadatafield>\n        <qtimetadatafield>\n          <fieldlabel>identicalScoring</fieldlabel>\n          <fieldentry>1</fieldentry>\n        </qtimetadatafield>\n      </qtimetadata>\n    </itemmetadata>\n"  # depending on question type

# Question presentation (whole question open/close)
itempresentationopen = (
    '    <presentation label="%s">\n      <flow>\n'  # depending on title
)
itempresentationclose = "      </flow>\n    </presentation>\n"

# Question presentation (question parts)
insertquestiontext = '        <material>\n          <mattext texttype="text/xhtml">%s%s%s</mattext>\n        </material>\n'  # depending on text
insertgap = '        <response_str ident="gap_%i" rcardinality="Single">\n          <render_fib fibtype="String" prompt="Box" columns="0">\n          </render_fib>\n        </response_str>\n'  # depending on gap id
insertMCsingleopen = '        <response_lid ident="MCSR" rcardinality="Single">\n          <render_choice shuffle="Yes">\n'
insertMCmultiopen = '        <response_lid ident="MCMR" rcardinality="Multiple">\n          <render_choice shuffle="Yes">\n'
insertMCclose = "      </render_choice>\n   </response_lid>\n"
insertMC = '            <response_label ident="%i">\n               <material>\n                 <mattext texttype="text/plain">%s</mattext>\n             </material>\n         </response_label>\n'  # depending on item id and text

# Question responses/answers (whole question open/close)
itemresprocessingopen = "    <resprocessing>\n      <outcomes>\n        <decvar>\n        </decvar>\n      </outcomes>\n"
itemresprocessingclose = "    </resprocessing>\n"

# Question responses/answers (question parts)
itemresprocessingGap = '      <respcondition continue="Yes">\n        <conditionvar>\n          <varequal respident="gap_%i">%s</varequal>\n        </conditionvar>\n        <setvar action="Add">%f</setvar>\n        <displayfeedback feedbacktype="Response" linkrefid="%i_Response_0"/>\n      </respcondition>\n'  # depends on gap id, points
itemresprocessingMCChecked = '      <respcondition continue="Yes">\n        <conditionvar>\n          <varequal respident="MCSR">%i</varequal>\n        </conditionvar>\n        <setvar action="Add">%f</setvar>\n        <displayfeedback feedbacktype="Response" linkrefid="response_%i"/>\n      </respcondition>\n'  # depends on answer id, points, answer id
itemresprocessingMCUnchecked = '      <respcondition continue="Yes">\n        <conditionvar>\n          <not>\n          <varequal respident="MCSR">%i</varequal>\n          </not>\n        </conditionvar>\n        <setvar action="Add">%f</setvar>\n        <displayfeedback feedbacktype="Response" linkrefid="Response_%i"/>\n      </respcondition>\n'  # depends on answer id, points, answer id


# Question feedback (whole question)
itemfeedbackGap = '    <itemfeedback ident="%i_Response_0" view="All">\n      <flow_mat>\n        <material>\n          <mattext/>\n        </material>\n      </flow_mat>\n    </itemfeedback>\n'
itemfeedbackMC = '    <itemfeedback ident="response_%i" view="All">\n      <flow_mat>\n        <material>\n          <mattext/>\n        </material>\n      </flow_mat>\n    </itemfeedback>\n'


# used to split the text into parts
# Gaps: each gap is surrounded by [gap][/gap]
gapre = "\[gap\]([^\[\]]*)\[/gap\]"
# multiple choice: Either - or _ at beginning of line followed by space
mcre = "&lt;br/&gt;- "


def createQuestion(questionType, questionText, totalPoints=1):

    # Prepare
    itempresentationelems = ""
    itemfeedbackelems = ""
    itemresprocessingelems = ""

    # Gap questions
    if questionType == questionTypeGap:
        textparts = re.split(gapre, questionText)
        # should give totalPoints in total, each gap = totalPoints/#gaps
        gap_count = len(textparts) // 2
        points = round(totalPoints / gap_count, 2)
        #  print "we have %i parts = %i gaps = %f points per gap" % (len(textparts), ( len(textparts) / 2.0), points) # TEST !!!
        for i in range(0, len(textparts)):
            before = ""
            if i == 0:  # first item (start paragraph)
                before = "&lt;p&gt;"
            after = ""
            if i == len(textparts) - 1:  # last item (end paragraph)
                after = "&lt;/p&gt;"

            gaptext = textparts[i]
            if i % 2 == 0:  # Outside of gap
                itempresentationelems += insertquestiontext % (before, gaptext, after)
            else:  # inside of gap
                gapno = i // 2
                if (
                    i >= len(textparts) - 2
                ):  # this is the last gap, add remainder of points
                    points = totalPoints - (gapno) * points
                itempresentationelems += insertgap % (gapno)
                itemresprocessingelems += itemresprocessingGap % (
                    gapno,
                    gaptext,
                    points,
                    gapno,
                )
                itemfeedbackelems += itemfeedbackGap % (gapno)
        print("   have %d gaps, %d point(s) in total" % (len(textparts) - 1, points))

    # Multiple choice questions
    elif questionType == questionTypeMCSingle or questionType == questionTypeMCMulti:
        multi = False
        if questionType == questionTypeMCMulti:
            multi = True

        questionText = re.sub("&lt;br/&gt;_", "&lt;br/&gt;- _", questionText)
        textparts = re.split(mcre, questionText)

        # Question text
        before = "&lt;p&gt;"
        after = "&lt;/p&gt;"
        itempresentationelems += insertquestiontext % (before, textparts[0], after)
        if multi:
            itempresentationelems += insertMCmultiopen
        else:
            itempresentationelems += insertMCsingleopen

        # Points
        if multi:  # multiple correct answers: should give totalPoints in total, each item = totalPoints/#items
            points = round(totalPoints / (len(textparts) - 1), 2)
        else:  # single correct answer = totalPoints points
            points = totalPoints
        pointsassigned = 0  # sanity check

        # Answer possibilities
        for i in range(1, len(textparts)):
            parttext = textparts[i]
            answerid = i - 1

            if (
                i == len(textparts) - 1 and multi
            ):  # last item and multiple selection possible, add remainder of points # TODO this is a little bit unfair
                #  points = totalPoints - ((len(textparts)-2) * points)
                points = totalPoints - pointsassigned

            if parttext[0:1] == "_":  # correct when checked
                itempresentationelems += insertMC % (answerid, parttext[2:])
                itemresprocessingelems += itemresprocessingMCChecked % (
                    answerid,
                    points,
                    answerid,
                )
                pointsassigned += points  # sanity check
                if multi:  # add also what happens if NOT checked
                    itemresprocessingelems += itemresprocessingMCUnchecked % (
                        answerid,
                        0,
                        answerid,
                    )

            else:  # wrong when checked, i.e., correct when unchecked
                itempresentationelems += insertMC % (answerid, parttext)
                itemresprocessingelems += itemresprocessingMCChecked % (
                    answerid,
                    0,
                    answerid,
                )
                if multi:  # add also what happens if NOT checked
                    itemresprocessingelems += itemresprocessingMCUnchecked % (
                        answerid,
                        points,
                        answerid,
                    )
                    pointsassigned += points  # sanity check
            itemfeedbackelems += itemfeedbackMC % (answerid)

        if pointsassigned != 1.0:  # sanity check
            print(
                "!! WARNING !! something is wrong, I just assigned %.2f points to this questions!"
                % (pointsassigned)
            )
        itempresentationelems += insertMCclose
        print(
            "   have %d answer choices, %d point(s) in total"
            % (len(textparts) - 1, pointsassigned)
        )

    else:
        print("!! ERROR !! something is wrong, I don't know this type of question.")
        return None, None, None

    return itempresentationelems, itemfeedbackelems, itemresprocessingelems


def convertFile(inputFile, outputFile, filterPoints=None):
    """
    Convert input file to QTI XML format.
    If filterPoints is specified, only include questions with that point value.
    """

    outputFile.write(header)

    lineno = 0
    inItem = False
    questionText = ""
    questionType = ""
    questionTitle = ""
    questionId = ""
    questionPoints = 1
    questionno = 0

    for line in inputFile:
        line = line.strip()
        lineno += 1

        if line == "" and inItem:  # End of item -> prepare, print & reset
            # Skip this question if it doesn't match the filter
            if filterPoints is not None and questionPoints != filterPoints:
                questionText = ""
                questionType = ""
                questionTitle = ""
                inItem = False
                continue

            questionno += 1

            # Prepare question
            print(questionId + " " + questionType + " " + questionTitle)  # TEST !!!
            itempresentationelems, itemfeedbackelems, itemresprocessingelems = (
                createQuestion(questionType, questionText, questionPoints)
            )

            # Print
            if itempresentationelems is not None:
                outputFile.write(itemopen % (questionId, questionTitle))
                outputFile.write(itemmetadata % questionType)
                outputFile.write(itempresentationopen % (questionTitle))
                outputFile.write(itempresentationelems)
                outputFile.write(itempresentationclose)
                outputFile.write(itemresprocessingopen)
                outputFile.write(itemresprocessingelems)
                outputFile.write(itemresprocessingclose)
                outputFile.write(itemfeedbackelems)
                outputFile.write(itemclose)

            # Reset
            questionText = ""
            questionType = ""
            questionTitle = ""
            inItem = False
            continue

        if line == "" and not inItem:  # Ignore empty lines
            continue

        if line[0] == "#":  # Ignore comments
            continue

        if line[0:3] == "[t]":  # Have title -> create new question
            inItem = True
            questionId = "il_0_qst_" + str(lineno)  # id comes from line number

            # Type
            if line[3:6] == "[s]":  # multiple choice, single answer
                questionType = questionTypeMCSingle
            elif line[3:6] == "[m]":  # multiple choice, multiple answers
                questionType = questionTypeMCMulti
            elif line[3:6] == "[g]":  # gap question
                questionType = questionTypeGap

            # Title and points
            titleWithPoints = line[6:].strip()
            # Extract points if specified as @X at end of title
            questionPoints = 1  # default
            if "@" in titleWithPoints:
                parts = titleWithPoints.rsplit("@", 1)
                questionTitle = parts[0].strip()
                try:
                    questionPoints = float(parts[1].strip())
                except ValueError:
                    questionTitle = titleWithPoints  # If conversion fails, treat whole thing as title
            else:
                questionTitle = titleWithPoints
            continue

        # Have (maybe several lines) of question text
        # Just add this to what I have had before
        if questionText == "":
            questionText = line
        else:
            questionText = questionText + "&lt;br/&gt;" + line

    outputFile.write(footer)
    print("Found %d questions.\n" % (questionno))
    return questionno


#### MAIN ####


def extractPointValues(inputFilename):
    """Extract all unique point values from the input file"""
    pointValues = set()
    try:
        with open(inputFilename, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line[0:3] == "[t]":
                    titleWithPoints = line[6:].strip()
                    if "@" in titleWithPoints:
                        parts = titleWithPoints.rsplit("@", 1)
                        try:
                            points = float(parts[1].strip())
                            pointValues.add(points)
                        except ValueError:
                            pass
    except Exception:
        pass

    return sorted(list(pointValues)) if pointValues else [1]


def extractMetadata(inputFilename):
    """Extract title and description from input file"""
    title = os.path.splitext(os.path.basename(inputFilename))[0]
    description = ""

    try:
        with open(inputFilename, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line.startswith("# TITLE:"):
                    title = line[8:].strip()
                elif line.startswith("# DESCRIPTION:"):
                    description = line[14:].strip()
    except Exception:
        pass

    return title, description


def createManifest(qplId, title, description, qtiId):
    """Create the ILIAS question pool manifest XML"""
    manifest = """<?xml version="1.0" encoding="utf-8"?><!DOCTYPE Test SYSTEM "http://www.ilias.uni-koeln.de/download/dtd/ilias_co.dtd"><!--Export of ILIAS Test Questionpool {qplId} of installation 1600--><ContentObject Type="Questionpool_Test"><MetaData><General Structure="Hierarchical"><Identifier Catalog="ILIAS" Entry="il_1600_qpl_{qplId}"/><Title Language="de">{title}</Title><Language Language="de"/><Description Language="de">{description}</Description><Keyword Language="de"></Keyword></General></MetaData><Settings><ShowTaxonomies>0</ShowTaxonomies><SkillService>0</SkillService></Settings><PageObject><PageContent><Question QRef="il_1600_qst_{qtiId}"/></PageContent></PageObject><QuestionSkillAssignments><TriggerQuestion Id="{qtiId}"></TriggerQuestion></QuestionSkillAssignments></ContentObject>"""
    return manifest.format(
        qplId=qplId, title=title, description=description, qtiId=qtiId
    )


def createIliasArchive(qtiContent, outputDir, title, description, uniqueId=None):
    """Create ILIAS-compatible archive structure from in-memory QTI XML content"""
    if uniqueId is None:
        # Keep behavior deterministic when caller does not provide an ID.
        uniqueId = "0000000"

    # Build a deterministic timestamp-like number from stable pool data.
    fingerprint = f"{uniqueId}\n{title}\n{description}\n{qtiContent}".encode("utf-8")
    digest = hashlib.sha1(fingerprint).hexdigest()
    timestamp_int = int(digest[:12], 16) % 9000000000 + 1000000000
    timestamp = str(timestamp_int)

    qplId = uniqueId  # Use provided unique ID
    qtiId = uniqueId  # Use provided unique ID

    # Create folder structure
    folderName = timestamp + "__1600__qpl_" + qplId
    tempDir = os.path.join(outputDir, folderName)

    if os.path.exists(tempDir):
        shutil.rmtree(tempDir)
    os.makedirs(os.path.join(tempDir, "objects"))

    # Create manifest file
    manifestFilename = os.path.join(
        tempDir, timestamp + "__1600__qpl_" + qplId + ".xml"
    )
    manifest = createManifest(qplId, title, description, qtiId)
    with open(manifestFilename, "w", encoding="utf-8") as f:
        f.write(manifest)

    # Write QTI file into archive structure
    qtiDestFilename = os.path.join(tempDir, timestamp + "__1600__qti_" + qplId + ".xml")
    with open(qtiDestFilename, "w", encoding="utf-8") as f:
        f.write(qtiContent)

    # Create zip archive
    zipFilename = os.path.join(outputDir, folderName + ".zip")
    with zipfile.ZipFile(zipFilename, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for root, dirs, files in os.walk(tempDir):
            for file in files:
                filePath = os.path.join(root, file)
                arcname = os.path.relpath(filePath, os.path.dirname(tempDir))
                zf.write(filePath, arcname)

    # Clean up temp directory
    shutil.rmtree(tempDir)

    return zipFilename


def updatePoolOverviewCsv(
    outputDir, overviewRows, overviewFilename="pool_overview.csv"
):
    """Update an overview CSV with one row per generated pool zip file."""
    if not overviewRows:
        return None

    overviewPath = os.path.join(outputDir, overviewFilename)
    fieldnames = [
        "pool_zip_name",
        "ilias_pool_name",
        "question_count",
        "points_per_question",
    ]

    mergedRows = {}

    if os.path.exists(overviewPath):
        with open(overviewPath, "r", encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                poolZipName = row.get("pool_zip_name", "").strip()
                if poolZipName:
                    mergedRows[poolZipName] = {
                        "pool_zip_name": poolZipName,
                        "ilias_pool_name": row.get("ilias_pool_name", ""),
                        "question_count": row.get("question_count", ""),
                        "points_per_question": row.get("points_per_question", ""),
                    }

    for row in overviewRows:
        poolZipName = str(row.get("pool_zip_name", "")).strip()
        if not poolZipName:
            continue
        mergedRows[poolZipName] = {
            "pool_zip_name": poolZipName,
            "ilias_pool_name": row.get("ilias_pool_name", ""),
            "question_count": row.get("question_count", ""),
            "points_per_question": row.get("points_per_question", ""),
        }

    with open(overviewPath, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for poolZipName in sorted(mergedRows.keys()):
            writer.writerow(mergedRows[poolZipName])

    return overviewPath, list(mergedRows.values())


def _formatPointLabel(points):
    """Format point values for readable CSV headers/labels."""
    if points.denominator == 1:
        return str(points.numerator)
    return f"{points.numerator}_{points.denominator}"


def _buildCombinationText(pointsByCategory, countsByCategory):
    """Create compact text like '2x3pt + 7x2pt'."""
    parts = []
    for points in sorted(pointsByCategory, reverse=True):
        count = countsByCategory.get(points, 0)
        if count > 0:
            parts.append(f"{count}x{_formatPointLabel(points)}pt")
    return " + ".join(parts) if parts else "0"


def exportTargetPointCombinationsCsv(
    outputDir,
    overviewRows,
    targetPoints=20,
    combinationsFilename=None,
    maxCombinations=12,
):
    """Export a curated set of balanced combinations that sum to targetPoints."""
    if not overviewRows:
        return None, 0

    try:
        target = Fraction(str(targetPoints).strip())
    except (ValueError, ZeroDivisionError):
        raise ValueError(f"Invalid targetPoints value: {targetPoints}")

    if target <= 0:
        raise ValueError("targetPoints must be > 0")

    if combinationsFilename is None:
        combinationsFilename = (
            f"pool_combinations_{_formatPointLabel(target)}_points.csv"
        )

    categories = []
    for row in overviewRows:
        try:
            points = Fraction(str(row.get("points_per_question", "")).strip())
            questionCount = int(float(str(row.get("question_count", "")).strip()))
        except (ValueError, ZeroDivisionError):
            continue

        if points <= 0 or questionCount <= 0:
            continue
        categories.append((points, questionCount))

    if not categories:
        return None, 0

    # If duplicate point categories exist, keep the largest available question count.
    maxCountByPoints = {}
    for points, questionCount in categories:
        maxCountByPoints[points] = max(maxCountByPoints.get(points, 0), questionCount)

    sortedPoints = sorted(maxCountByPoints.keys(), reverse=True)
    combinations = []

    def backtrack(idx, remaining, selection):
        if idx == len(sortedPoints):
            if remaining == 0:
                combinations.append(selection.copy())
            return

        points = sortedPoints[idx]
        maxByPoints = int(remaining / points)
        maxByAvailability = maxCountByPoints[points]
        maxUse = min(maxByPoints, maxByAvailability)

        for count in range(maxUse, -1, -1):
            selection[points] = count
            backtrack(idx + 1, remaining - points * count, selection)

    backtrack(0, target, {})

    def balanceScore(selection):
        """
        Lower score means more balanced question counts across used point categories.
        Single-category solutions are intentionally penalized.
        """
        counts = [
            selection.get(points, 0)
            for points in sortedPoints
            if selection.get(points, 0) > 0
        ]
        if len(counts) <= 1:
            return 9999.0
        meanCount = sum(counts) / float(len(counts))
        return sum(abs(count - meanCount) for count in counts) / float(len(counts))

    scored = []
    for selection in combinations:
        usedCategoryCount = sum(
            1 for points in sortedPoints if selection.get(points, 0) > 0
        )
        totalQuestions = sum(selection.get(points, 0) for points in sortedPoints)
        scored.append(
            {
                "selection": selection,
                "used_categories": usedCategoryCount,
                "total_questions": totalQuestions,
                "balance_score": round(balanceScore(selection), 3),
            }
        )

    # Rank by: more used categories, better balance, then fewer questions for compact quizzes.
    scored.sort(
        key=lambda item: (
            -item["used_categories"],
            item["balance_score"],
            item["total_questions"],
            _buildCombinationText(sortedPoints, item["selection"]),
        )
    )

    curated = scored[:maxCombinations]

    combinationPath = os.path.join(outputDir, combinationsFilename)
    dynamicCountHeaders = [f"count_{_formatPointLabel(p)}pt" for p in sortedPoints]
    fieldnames = [
        "rank",
        "target_points",
        "total_questions",
        "used_point_categories",
        "balance_score",
        "combination",
    ] + dynamicCountHeaders

    with open(combinationPath, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for idx, item in enumerate(curated, start=1):
            selection = item["selection"]
            row = {
                "rank": idx,
                "target_points": float(target),
                "total_questions": item["total_questions"],
                "used_point_categories": item["used_categories"],
                "balance_score": item["balance_score"],
                "combination": _buildCombinationText(sortedPoints, selection),
            }
            for points in sortedPoints:
                row[f"count_{_formatPointLabel(points)}pt"] = selection.get(points, 0)
            writer.writerow(row)

    return combinationPath, len(curated)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Create ILIAS pools and a balanced quiz-combination overview."
    )
    parser.add_argument(
        "input_files",
        nargs="+",
        help="One or more input question text files",
    )
    parser.add_argument(
        "-t",
        "--target-points",
        default="20",
        help="Target total points for quiz combinations (default: 20)",
    )

    args = parser.parse_args()

    try:
        targetPoints = Fraction(str(args.target_points).strip())
    except (ValueError, ZeroDivisionError):
        print(
            f"Error! Invalid value for --target-points: {args.target_points}. Use values like 20 or 12.5"
        )
        sys.exit(1)

    if targetPoints <= 0:
        print("Error! --target-points must be greater than 0")
        sys.exit(1)

    targetLabel = _formatPointLabel(targetPoints)

    overviewRowsByDir = {}

    for inputFilename in args.input_files:
        baseTitle, description = extractMetadata(inputFilename)
        pointValues = extractPointValues(inputFilename)

        print(f"\n... processing file {inputFilename}")
        print(f"   Title: {baseTitle}")
        print(f"   Description: {description}")
        print(f"   Found point values: {pointValues}")

        for points in pointValues:
            print(f"\n... generating pool for {int(points)} point(s)")

            # Generate QTI XML with filter for specific point value in memory
            qtiBuffer = io.StringIO()
            with open(inputFilename, encoding="utf-8") as inputFile:
                questionCount = convertFile(inputFile, qtiBuffer, filterPoints=points)
            qtiContent = qtiBuffer.getvalue()

            # Create ILIAS archive with unique ID based on points
            poolTitle = f"{baseTitle} ({int(points)} points)"
            uniqueId = str(
                6599700 + int(points)
            )  # Generate unique IDs like 6599701, 6599702, 6599703
            outputDir = os.path.dirname(inputFilename) or "."
            archiveFilename = createIliasArchive(
                qtiContent,
                outputDir,
                poolTitle,
                description,
                uniqueId=uniqueId,
            )
            print(f"... created archive {archiveFilename}")

            overviewRowsByDir.setdefault(outputDir, []).append(
                {
                    "pool_zip_name": os.path.basename(archiveFilename),
                    "ilias_pool_name": poolTitle,
                    "question_count": questionCount,
                    "points_per_question": points,
                }
            )

    for outputDir, overviewRows in overviewRowsByDir.items():
        overviewPath, _mergedRows = updatePoolOverviewCsv(outputDir, overviewRows)
        if overviewPath is not None:
            print(f"... updated pool overview {overviewPath}")

        combinationsPath, combinationCount = exportTargetPointCombinationsCsv(
            outputDir,
            overviewRows,
            targetPoints=targetPoints,
            combinationsFilename=f"pool_combinations_{targetLabel}_points.csv",
        )
        if combinationsPath is not None:
            print(
                f"... exported {combinationCount} possible {float(targetPoints)}-point combinations to {combinationsPath}"
            )
