"""QTI XML converter for iliasqc."""

from __future__ import annotations

import re

from iliasqc.parser import (
    QUESTION_TYPE_GAP,
    QUESTION_TYPE_MC_MULTI,
    QUESTION_TYPE_MC_SINGLE,
    Question,
)

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questestinterop SYSTEM "ims_qtiasiv1p2p1.dtd">
<!--Generated by ILIAS XmlWriter-->
<questestinterop>
"""

FOOTER = "</questestinterop>\n"

ITEM_OPEN = '  <item ident="{ident}" title="{title}" maxattempts="1">\n'
ITEM_CLOSE = "  </item>\n"

ITEM_METADATA = """    <qticomment/>
    <duration>P0Y0M0DT0H1M0S</duration>
    <itemmetadata>
      <qtimetadata>
        <qtimetadatafield>
          <fieldlabel>ILIAS_VERSION</fieldlabel>
          <fieldentry>9.18.0</fieldentry>
        </qtimetadatafield>
        <qtimetadatafield>
          <fieldlabel>QUESTIONTYPE</fieldlabel>
          <fieldentry>{question_type}</fieldentry>
        </qtimetadatafield>
        <qtimetadatafield>
          <fieldlabel>AUTHOR</fieldlabel>
          <fieldentry>iliasqc - ILIAS Question Converter</fieldentry>
        </qtimetadatafield>
        <qtimetadatafield>
          <fieldlabel>textgaprating</fieldlabel>
          <fieldentry>cs</fieldentry>
        </qtimetadatafield>
        <qtimetadatafield>
          <fieldlabel>fixedTextLength</fieldlabel>
          <fieldentry/>
        </qtimetadatafield>
        <qtimetadatafield>
          <fieldlabel>identicalScoring</fieldlabel>
          <fieldentry>1</fieldentry>
        </qtimetadatafield>
      </qtimetadata>
    </itemmetadata>
"""

PRESENTATION_OPEN = '    <presentation label="{title}">\n      <flow>\n'
PRESENTATION_CLOSE = "      </flow>\n    </presentation>\n"

MATERIAL_TEMPLATE = '        <material>\n          <mattext texttype="text/xhtml">{text}</mattext>\n        </material>\n'

GAP_TEMPLATE = """        <response_str ident="gap_{gap_no}" rcardinality="Single">
          <render_fib fibtype="String" prompt="Box" columns="0">
          </render_fib>
        </response_str>
"""

MC_SINGLE_OPEN = """        <response_lid ident="MCSR" rcardinality="Single">
          <render_choice shuffle="Yes">
"""
MC_MULTI_OPEN = """        <response_lid ident="MCMR" rcardinality="Multiple">
          <render_choice shuffle="Yes">
"""
MC_CLOSE = "      </render_choice>\n   </response_lid>\n"

MC_LABEL_TEMPLATE = """            <response_label ident="{ident}">
               <material>
                 <mattext texttype="text/plain">{text}</mattext>
             </material>
         </response_label>
"""

RESPONSE_PROCESSING_OPEN = """    <resprocessing>
      <outcomes>
        <decvar varname="SCORE" vartype="Integer" minvalue="0" maxvalue="{points}"/>
      </outcomes>
"""
RESPONSE_PROCESSING_OPEN_DEFAULT = """    <resprocessing>
      <outcomes>
        <decvar varname="SCORE" vartype="Integer" minvalue="0" maxvalue="1"/>
      </outcomes>
"""
RESPONSE_PROCESSING_CLOSE = "    </resprocessing>\n"

RESP_CONDITION_GAP = """      <respcondition continue="Yes">
        <conditionvar>
          <varequal respident="gap_{gap_no}">{answer}</varequal>
        </conditionvar>
        <setvar action="Add">{points}</setvar>
        <displayfeedback feedbacktype="Response" linkrefid="{gap_no}_Response_0"/>
      </respcondition>
"""

RESP_CONDITION_MC_CHECKED = """      <respcondition continue="Yes">
        <conditionvar>
          <varequal respident="{resp_ident}">{answer_id}</varequal>
        </conditionvar>
        <setvar action="Add">{points}</setvar>
        <displayfeedback feedbacktype="Response" linkrefid="response_{answer_id}"/>
      </respcondition>
"""

RESP_CONDITION_MC_UNCHECKED = """      <respcondition continue="Yes">
        <conditionvar>
          <not>
          <varequal respident="{resp_ident}">{answer_id}</varequal>
          </not>
        </conditionvar>
        <setvar action="Add">{points}</setvar>
        <displayfeedback feedbacktype="Response" linkrefid="Response_{answer_id}"/>
      </respcondition>
"""

ITEM_FEEDBACK_GAP = """    <itemfeedback ident="{gap_no}_Response_0" view="All">
      <flow_mat>
        <material>
          <mattext/>
        </material>
      </flow_mat>
    </itemfeedback>
"""

ITEM_FEEDBACK_MC = """    <itemfeedback ident="response_{answer_id}" view="All">
      <flow_mat>
        <material>
          <mattext/>
        </material>
      </flow_mat>
    </itemfeedback>
"""

GAP_RE = r"\[gap\]([^\[\]]*)\[/gap\]"


def _escape_xml(text: str) -> str:
    """Escape special XML characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&apos;")
    )


def _html_to_xhtml(text: str) -> str:
    """Convert HTML-style line breaks to XHTML."""
    return text.replace("<br/>", "&lt;br/&gt;")


def create_question(question: Question) -> tuple[str, str, str]:
    """Create QTI XML elements for a single question.

    Parameters
    ----------
    question:
        The Question object to convert.

    Returns
    -------
    tuple[str, str, str]
        A tuple of (presentation, feedback, resprocessing) XML strings.
    """
    presentation_elems = ""
    feedback_elems = ""
    resprocessing_elems = ""

    if question.question_type == QUESTION_TYPE_GAP:
        textparts = re.split(GAP_RE, question.text)
        gap_count = len(textparts) // 2
        points = round(question.points / gap_count, 2)

        for i, part in enumerate(textparts):
            before = ""
            if i == 0:
                before = "&lt;p&gt;"
            after = ""
            if i == len(textparts) - 1:
                after = "&lt;/p&gt;"

            if i % 2 == 0:
                escaped = _escape_xml(part)
                presentation_elems += MATERIAL_TEMPLATE.format(text=before + escaped + after)
            else:
                gap_no = i // 2
                if i >= len(textparts) - 2:
                    points = question.points - (gap_no) * round(question.points / gap_count, 2)
                presentation_elems += GAP_TEMPLATE.format(gap_no=gap_no)
                resprocessing_elems += RESP_CONDITION_GAP.format(
                    gap_no=gap_no,
                    answer=_escape_xml(part),
                    points=points,
                )
                feedback_elems += ITEM_FEEDBACK_GAP.format(gap_no=gap_no)

    elif question.question_type in (QUESTION_TYPE_MC_SINGLE, QUESTION_TYPE_MC_MULTI):
        is_multi = question.question_type == QUESTION_TYPE_MC_MULTI

        mc_split_pattern = "<br/>- "
        normalized_text = question.text.replace("<br/>_", "<br/>- _")
        parts = normalized_text.split(mc_split_pattern)

        question_part = ""
        answer_texts: list[str] = []
        for i, part in enumerate(parts):
            if i == 0:
                if part.startswith("_ ") or part.startswith("- "):
                    answer_texts.append(part)
                else:
                    question_part = part
            else:
                answer_texts.append(part)

        answer_texts = [t for t in answer_texts if t]

        escaped = _escape_xml(question_part)
        presentation_elems += MATERIAL_TEMPLATE.format(text="&lt;p&gt;" + escaped + "&lt;/p&gt;")

        if is_multi:
            presentation_elems += MC_MULTI_OPEN
        else:
            presentation_elems += MC_SINGLE_OPEN

        if is_multi:
            points_per_answer = round(question.points / len(answer_texts), 2)
        else:
            points_per_answer = question.points
        points_assigned = 0.0

        for i, answer in enumerate(question.answers):
            answer_id = i
            answer_text = _escape_xml(answer.text)

            presentation_elems += MC_LABEL_TEMPLATE.format(ident=answer_id, text=answer_text)

            if answer.is_correct:
                resp_ident = "MCMR" if is_multi else "MCSR"
                resprocessing_elems += RESP_CONDITION_MC_CHECKED.format(
                    resp_ident=resp_ident,
                    answer_id=answer_id,
                    points=points_per_answer,
                )
                points_assigned += points_per_answer

                if is_multi:
                    resprocessing_elems += RESP_CONDITION_MC_UNCHECKED.format(
                        resp_ident=resp_ident,
                        answer_id=answer_id,
                        points=0,
                    )
            else:
                resp_ident = "MCMR" if is_multi else "MCSR"
                if is_multi:
                    resprocessing_elems += RESP_CONDITION_MC_UNCHECKED.format(
                        resp_ident=resp_ident,
                        answer_id=answer_id,
                        points=points_per_answer,
                    )
                    points_assigned += points_per_answer
                else:
                    resprocessing_elems += RESP_CONDITION_MC_CHECKED.format(
                        resp_ident=resp_ident,
                        answer_id=answer_id,
                        points=0,
                    )

            feedback_elems += ITEM_FEEDBACK_MC.format(answer_id=answer_id)

        presentation_elems += MC_CLOSE

    return presentation_elems, feedback_elems, resprocessing_elems


def convert_to_qti(questions: list[Question]) -> str:
    """Convert a list of questions to QTI XML format.

    Parameters
    ----------
    questions:
        List of Question objects to convert.

    Returns
    -------
    str
        Complete QTI XML document as a string.
    """
    output = HEADER

    for question in questions:
        presentation_elems, feedback_elems, resprocessing_elems = create_question(question)

        points = float(question.points)
        rp_open = RESPONSE_PROCESSING_OPEN.format(points=int(points))

        output += ITEM_OPEN.format(ident=question.question_id, title=question.title)
        output += ITEM_METADATA.format(question_type=question.question_type)
        output += PRESENTATION_OPEN.format(title=question.title)
        output += presentation_elems
        output += PRESENTATION_CLOSE
        output += rp_open
        output += resprocessing_elems
        output += RESPONSE_PROCESSING_CLOSE
        output += feedback_elems
        output += ITEM_CLOSE

    output += FOOTER
    return output
