"""ILIAS quiz/test generation for iliasqc.

This module handles generating ILIAS quiz/export archives from question pool
combinations. The quiz format is similar to pools but uses test (tst)
structure instead of pool (qpl).
"""

from __future__ import annotations

import hashlib
import os
import shutil
import zipfile
from dataclasses import dataclass
from pathlib import Path


@dataclass
class QuizQuestionRef:
    """A reference to a question from a pool."""

    question_id: str
    pool_zip_path: Path
    title: str
    points: float


def _generate_test_id(title: str, description: str, pool_refs: list[Path]) -> str:
    """Generate a deterministic test ID."""
    content = f"{title}\n{description}\n".encode()
    content += "\n".join(str(p) for p in pool_refs).encode()
    digest = hashlib.sha1(content).hexdigest()
    return digest[:12]


def create_test_manifest(tst_id: str, title: str, description: str, question_ids: list[str]) -> str:
    """Create the ILIAS test manifest XML.

    Parameters
    ----------
    tst_id:
        The test/assessment ID.
    title:
        The test title.
    description:
        The test description.
    question_ids:
        List of question IDs to include (without il_1600_qst_ prefix).

    Returns
    -------
    str
        The manifest XML as a string.
    """
    question_elements = ""
    for qid in question_ids:
        question_elements += f'<Question QRef="il_1600_qst_{qid}"/>\n'

    manifest = (
        '<?xml version="1.0" encoding="utf-8"?>'
        '<!DOCTYPE Test SYSTEM "http://www.ilias.uni-koeln.de/download/dtd/ilias_co.dtd">'
        f"<!--Export of ILIAS Test {tst_id} of installation 1600-->"
        '<ContentObject Type="Test">'
        "<MetaData>"
        '<General Structure="Hierarchical">'
        f'<Identifier Catalog="ILIAS" Entry="il_1600_tst_{tst_id}"/>'
        f'<Title Language="en">{title}</Title>'
        '<Language Language="en"/>'
        f'<Description Language="en">{description}</Description>'
        '<Keyword Language="en"></Keyword>'
        "</General>"
        "</MetaData>"
        "<Settings>"
        "<TestType>0</TestType>"
        "<ScoreReporting>3</ScoreReporting>"
        "<MarkedAnswers>0</MarkedAnswers>"
        "<ShowManScoring>1</ShowManScoring>"
        "<Password></Password>"
        "<AllowedUsers></AllowedUsers>"
        "<allowedUserRoles></allowedUserRoles>"
        "<ShowAnswers>1</ShowAnswers>"
        "</Settings>"
        "<PageObject>"
        "<PageContent>"
        f"{question_elements}"
        "</PageContent>"
        "</PageObject>"
        "</ContentObject>"
    )
    return manifest


def create_test_export_xml(tst_id: str, question_ids: list[str]) -> str:
    """Create the ILIAS test export.xml file."""
    items = ""
    for qid in question_ids:
        items += f'<exp:ExportItem Id="{qid}"></exp:ExportItem>\n'

    return (
        '<?xml version="1.0" encoding="utf-8"?>'
        "<!--Generated by ILIAS XmlWriter-->"
        '<exp:Export InstallationId="1600" InstallationUrl="https://example.ilias.de" '
        'Entity="tst" SchemaVersion="4.1.0" '
        'xmlns:exp="http://www.ilias.de/Services/Export/exp/4_1" '
        'xmlns="http://www.ilias.de/Modules/Test/htlm/4_1">'
        f'<exp:ExportItem Id="{tst_id}"></exp:ExportItem>'
        "</exp:Export>"
    )


def create_test_manifest_file(
    tst_id: str,
    title: str,
    timestamp: str | None = None,
    nic: str = "1600",
) -> str:
    """Create the manifest.xml file for test export."""
    if timestamp is None:
        timestamp = "1234567890"

    tst_xml_path = f"{timestamp}__{nic}__tst_{tst_id}.xml"
    qti_xml_path = f"{timestamp}__{nic}__qti_{tst_id}.xml"
    export_xml_path = "Modules/Test/set_1/export.xml"
    mediaobjects_xml_path = "Services/MediaObjects/set_1/export.xml"
    file_xml_path = "Modules/File/set_1/export.xml"
    object_xml_path = "Services/Object/set_1/export.xml"

    export_files = [
        f'<ExportFile Component="Services/MediaObjects" Path="{mediaobjects_xml_path}"/>',
        f'<ExportFile Component="Modules/File" Path="{file_xml_path}"/>',
        f'<ExportFile Component="Modules/Test" Path="{tst_xml_path}"/>',
        f'<ExportFile Component="Modules/Test" Path="{qti_xml_path}"/>',
        f'<ExportFile Component="Modules/Test" Path="{export_xml_path}"/>',
        f'<ExportFile Component="Services/Object" Path="{object_xml_path}"/>',
    ]

    export_files_str = "\n".join(export_files)

    return (
        '<?xml version="1.0" encoding="utf-8"?>'
        "<!--Generated by ILIAS XmlWriter-->"
        f'<Manifest MainEntity="tst" Title="{title}" InstallationId="{nic}" '
        f'InstallationUrl="https://example.ilias.de">'
        "<Information>"
        "<MainEntity>tst</MainEntity>"
        "</Information>"
        f"{export_files_str}"
        "</Manifest>"
    )


def create_quiz_archive(
    pool_zip_paths: list[Path],
    output_dir: str | Path,
    title: str,
    description: str,
    unique_id: str | None = None,
) -> Path:
    """Create ILIAS-compatible quiz/test archive from pool combinations.

    This creates a test export that references questions from one or more
    pool zip files. The questions are not embedded - the test uses
    references to the pools that will be imported first.

    Parameters
    ----------
    pool_zip_paths:
        List of paths to pool zip files to include questions from.
    output_dir:
        Directory where the zip file will be created.
    title:
        The quiz/test title.
    description:
        The quiz description.
    unique_id:
        Optional unique ID. If not provided, generated from content.

    Returns
    -------
    Path
        Path to the created zip file.
    """
    if unique_id is None:
        unique_id = _generate_test_id(title, description, pool_zip_paths)

    pool_ids: list[str] = []
    for pool_path in pool_zip_paths:
        id_from_path = pool_path.stem[:12].replace("_", "").replace("-", "")
        if len(id_from_path) < 4:
            id_from_path = pool_path.name[:12]
        pool_ids.append(id_from_path)

    fingerprint = f"{unique_id}\n{title}\n{description}\n".encode()
    fingerprint += "\n".join(pool_ids).encode()
    digest = hashlib.sha1(fingerprint).hexdigest()
    timestamp_int = int(digest[:12], 16) % 9000000000 + 1000000000
    timestamp = str(timestamp_int)

    tst_id = unique_id[:12]
    pool_refs = [p[:12].ljust(12, "0") for p in pool_ids]

    output_dir = Path(output_dir)
    folder_name = f"{timestamp}__1600__tst_{tst_id}"
    temp_dir = output_dir / folder_name

    if temp_dir.exists():
        shutil.rmtree(temp_dir)
    temp_dir.mkdir(parents=True, exist_ok=True)

    (temp_dir / "objects").mkdir(exist_ok=True)

    export_dir = temp_dir / "Modules" / "Test" / "set_1"
    export_dir.mkdir(parents=True, exist_ok=True)
    export_xml = create_test_export_xml(tst_id, pool_refs)
    (export_dir / "export.xml").write_text(export_xml, encoding="utf-8")

    manifest_xml = create_test_manifest_file(tst_id, title, timestamp, "1600")
    (temp_dir / "manifest.xml").write_text(manifest_xml, encoding="utf-8")

    tst_filename = temp_dir / f"{timestamp}__1600__tst_{tst_id}.xml"
    tst_manifest = create_test_manifest(tst_id, title, description, pool_refs)
    tst_filename.write_text(tst_manifest, encoding="utf-8")

    for pool_path in pool_zip_paths:
        if pool_path.exists():
            copy_dir = temp_dir / "Modules" / "TestQuestionPool"
            copy_dir.mkdir(parents=True, exist_ok=True)
            pool_stem = pool_path.stem[:12].ljust(12, "0")
            dest_path = copy_dir / f"{pool_stem}_pool.zip"
            shutil.copy2(pool_path, dest_path)

    zip_filename = output_dir / f"{folder_name}.zip"
    with zipfile.ZipFile(zip_filename, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(folder_name + "/", "")
        for root, dirs, files in os.walk(temp_dir):
            for d in dirs:
                dir_path = Path(root) / d
                rel_path = dir_path.relative_to(temp_dir)
                zf.writestr(f"{folder_name}/{rel_path}/", "")
            for file in files:
                file_path = Path(root) / file
                arcname = file_path.relative_to(temp_dir.parent)
                zf.write(file_path, arcname)
        zf.writestr(f"{folder_name}/objects/./", "")

    shutil.rmtree(temp_dir)

    return zip_filename


def create_integrated_quiz_archive(
    qti_content: str,
    output_dir: str | Path,
    title: str,
    description: str,
    unique_id: str | None = None,
    question_ids: list[str] | None = None,
) -> Path:
    """Create ILIAS quiz archive with embedded questions (not pool references).

    This creates a quiz where the questions are embedded directly in the
    QTI file, rather than referencing external pools. This is useful when you
    want a self-contained quiz export.

    Parameters
    ----------
    qti_content:
        The QTI XML content as a string.
    output_dir:
        Directory where the zip file will be created.
    title:
        The quiz title.
    description:
        The quiz description.
    unique_id:
        Optional unique ID. If not provided, generated from content.
    question_ids:
        List of question IDs (e.g., ["123", "456"]) to include in the test.
        If not provided, extracted from qti_content.
    Returns
    -------
    Path
        Path to the created zip file.
    """
    import re

    if unique_id is None:
        unique_id = "0000000"

    if question_ids is None:
        qti_ids = re.findall(r'ident="il_1600_qst_(\d+)"', qti_content)
        question_ids = qti_ids if qti_ids else ["0"]

    qti_numerical_ids = []
    for qid in question_ids:
        if "il_0_qst_" in qid:
            qti_numerical_ids.append(qid.split("il_0_qst_")[-1])
        elif "il_1600_qst_" in qid:
            qti_numerical_ids.append(qid.split("il_1600_qst_")[-1])
        else:
            qti_numerical_ids.append(str(qid))

    fingerprint = f"{unique_id}\n{title}\n{description}\n{qti_content}".encode()
    digest = hashlib.sha1(fingerprint).hexdigest()
    timestamp_int = int(digest[:12], 16) % 9000000000 + 1000000000
    timestamp = str(timestamp_int)

    tst_id = unique_id[:12]

    output_dir = Path(output_dir)
    folder_name = f"{timestamp}__1600__tst_{tst_id}"
    temp_dir = output_dir / folder_name

    if temp_dir.exists():
        shutil.rmtree(temp_dir)
    temp_dir.mkdir(parents=True, exist_ok=True)

    (temp_dir / "objects").mkdir(exist_ok=True)

    export_dir = temp_dir / "Modules" / "Test" / "set_1"
    export_dir.mkdir(parents=True, exist_ok=True)
    export_xml = create_test_export_xml(tst_id, qti_numerical_ids)
    (export_dir / "export.xml").write_text(export_xml, encoding="utf-8")

    mediaobjects_dir = temp_dir / "Services" / "MediaObjects" / "set_1"
    mediaobjects_dir.mkdir(parents=True, exist_ok=True)
    mediaobjects_xml = '<?xml version="1.0" encoding="utf-8"?>\n'
    mediaobjects_xml += "<!--Generated by ILIAS XmlWriter-->\n"
    mediaobjects_xml += (
        '<exp:Export InstallationId="1600" InstallationUrl="https://example.ilias.de" '
    )
    mediaobjects_xml += 'Entity="mob" SchemaVersion="5.1.0" '
    mediaobjects_xml += 'xmlns:exp="http://www.ilias.de/Services/Export/exp/4_1" '
    mediaobjects_xml += 'xmlns="https://www.ilias.de/Services/MediaObjects/mob/5_1">'
    mediaobjects_xml += f'<exp:ExportItem Id="{tst_id}"></exp:ExportItem>'
    mediaobjects_xml += "</exp:Export>\n"
    (mediaobjects_dir / "export.xml").write_text(mediaobjects_xml, encoding="utf-8")

    file_dir = temp_dir / "Modules" / "File" / "set_1"
    file_dir.mkdir(parents=True, exist_ok=True)
    file_xml = '<?xml version="1.0" encoding="utf-8"?>\n'
    file_xml += "<!--Generated by ILIAS XmlWriter-->\n"
    file_xml += '<exp:Export InstallationId="1600" InstallationUrl="https://example.ilias.de" '
    file_xml += 'Entity="file" SchemaVersion="4.1.0" '
    file_xml += 'xmlns:exp="http://www.ilias.de/Services/Export/exp/4_1" '
    file_xml += 'xmlns="http://www.ilias.de/Modules/File/file/4_1">'
    file_xml += f'<exp:ExportItem Id="{tst_id}"></exp:ExportItem>'
    file_xml += "</exp:Export>\n"
    (file_dir / "export.xml").write_text(file_xml, encoding="utf-8")

    object_dir = temp_dir / "Services" / "Object" / "set_1"
    object_dir.mkdir(parents=True, exist_ok=True)
    object_xml = '<?xml version="1.0" encoding="utf-8"?>\n'
    object_xml += "<!--Generated by ILIAS XmlWriter-->\n"
    object_xml += '<exp:Export InstallationId="1600" InstallationUrl="https://example.ilias.de" '
    object_xml += 'Entity="common" SchemaVersion="5.4.0" '
    object_xml += 'xmlns:exp="http://www.ilias.de/Services/Export/exp/4_1" '
    object_xml += 'xmlns="http://www.ilias.de/Services/Object/obj/5_4">'
    object_xml += f'<exp:ExportItem Id="{tst_id}"></exp:ExportItem>'
    object_xml += "</exp:Export>\n"
    (object_dir / "export.xml").write_text(object_xml, encoding="utf-8")

    manifest_xml = create_test_manifest_file(tst_id, title, timestamp, "1600")
    (temp_dir / "manifest.xml").write_text(manifest_xml, encoding="utf-8")

    tst_filename = temp_dir / f"{timestamp}__1600__tst_{tst_id}.xml"
    tst_manifest = create_test_manifest(tst_id, title, description, qti_numerical_ids)
    tst_filename.write_text(tst_manifest, encoding="utf-8")

    qti_wrapped = _wrap_qti_in_assessment(qti_content, tst_id, title)
    nic = "1600"
    qti_filename = temp_dir / f"{timestamp}__{nic}__qti_{tst_id}.xml"
    qti_filename.write_text(qti_wrapped, encoding="utf-8")

    zip_filename = output_dir / f"{folder_name}.zip"
    with zipfile.ZipFile(zip_filename, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(folder_name + "/", "")
        for root, dirs, files in os.walk(temp_dir):
            for d in dirs:
                dir_path = Path(root) / d
                rel_path = dir_path.relative_to(temp_dir)
                zf.writestr(f"{folder_name}/{rel_path}/", "")
            for file in files:
                file_path = Path(root) / file
                arcname = file_path.relative_to(temp_dir.parent)
                zf.write(file_path, arcname)
        zf.writestr(f"{folder_name}/objects/./", "")

    shutil.rmtree(temp_dir)

    return zip_filename


def _wrap_qti_in_assessment(qti_content: str, test_id: str, title: str) -> str:
    """Wrap QTI question items in assessment and section elements."""
    header = f"""<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questestinterop SYSTEM "ims_qtiasiv1p2p1.dtd">
<!--Generated by ILIAS XmlWriter-->
<questestinterop>
<assessment ident="il_1600_tst_{test_id}" title="{title}">
<qticomment></qticomment>
<qtimetadata>
<qtimetadatafield><fieldlabel>ILIAS_VERSION</fieldlabel><fieldentry>9.18.0</fieldentry></qtimetadatafield>
<qtimetadatafield><fieldlabel>anonymity</fieldlabel><fieldentry>0</fieldentry></qtimetadatafield>
<qtimetadatafield><fieldlabel>question_set_type</fieldlabel><fieldentry>FIXED_QUEST_SET</fieldentry></qtimetadatafield>
<qtimetadatafield><fieldlabel>sequence_settings</fieldlabel><fieldentry>1</fieldentry></qtimetadatafield>
<qtimetadatafield><fieldlabel>author</fieldlabel><fieldentry>ILIASQC</fieldentry></qtimetadatafield>
<qtimetadatafield><fieldlabel>reset_processing_time</fieldlabel><fieldentry>0</fieldentry></qtimetadatafield>
<qtimetadatafield><fieldlabel>count_system</fieldlabel><fieldentry>0</fieldentry></qtimetadatafield>
</qtimetadata>
<section ident="il_1600_sec_{test_id}">
"""
    footer = """</section>
</assessment>
</questestinterop>
"""
    existing_content = qti_content.replace(
        """<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questestinterop SYSTEM "ims_qtiasiv1p2p1.dtd">
<!--Generated by ILIAS XmlWriter-->
<questestinterop>
""",
        "",
    )
    existing_content = existing_content.replace("</questestinterop>", "")
    return header + existing_content + footer
